name: Factions
version: ${project.version}
main: main.factions.Main
api-version: 1.17
commands:
  faction:
    description: Parent command.
    usage: /f <create | leave | join | disband | promote | menu>
    aliases: [f]
